In [1]:
import numpy as np

In [2]:
x=np.array([[1],[2],[3],[4],[5]])

In [3]:
x

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [4]:
y=np.array([1,3,2,3,5])

In [5]:
y

array([1, 3, 2, 3, 5])

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
teacher=LinearRegression()

In [8]:
learner=teacher.fit(x,y)

In [9]:
learner.predict([[1]])

array([1.2])

In [10]:
learner.coef_
#value of m

array([0.8])

In [11]:
learner.intercept_
#value of c

0.3999999999999999